- book/src/SUMMARY.md
- book/src/appendix/design.md
This is just throwing some ideas out there about my general ideas for the direction of Pikelet. This was prompted in part by my conversation with @freebroccolo on my [pikelet-categories gist](https://gist.github.com/brendanzab/9285eb8dfef5b6d6ccd87d90d6579590). Could do with more refinement, but hopefully it makes things a little clearer.
> Add some design thoughts to the documentation

- Cargo.toml
- src/cli/repl.rs
- src/syntax/core.rs
- src/syntax/pretty/concrete.rs
- src/syntax/translation/core_to_concrete.rs
> Use parens in concrete syntax when resugaring

- book/src/appendix/theory.md
- book/src/language/index.md
- book/src/language/type-inference.md
- src/semantics/errors.rs
- src/semantics/mod.rs
- src/semantics/tests/check.rs
- src/semantics/tests/check_module.rs
- src/semantics/tests/infer.rs
- src/semantics/tests/mod.rs
- src/semantics/tests/normalize.rs
- src/syntax/concrete.rs
- src/syntax/core.rs
- src/syntax/parse/grammar.lalrpop
- src/syntax/parse/lexer.rs
- src/syntax/pretty/concrete.rs
- src/syntax/pretty/core.rs
- src/syntax/translation/concrete_to_core.rs
- src/syntax/translation/core_to_concrete.rs
I was getting a little bogged down in PR #27 trying to finish implementing dependent records (see issue #24) all in one go. Instead I decided to just go ahead and implement non-dependent records for now.
> Implement simple, non-dependent records

- Cargo.toml
- src/cli/mod.rs
This moves some of the color argument stuff out into the reporting crate
> Bump codespan-reporting version

- src/syntax/concrete.rs
- src/syntax/core.rs
- src/syntax/pretty/concrete.rs
- src/syntax/pretty/core.rs
- src/syntax/pretty/mod.rs
This cuts out a bunch of complexity from the core pretty printing
> Simplify core pretty printing

- README.md
The current README is getting a little stale - it was left-over from when this was just an implementation of the [LambdaPi](https://www.andres-loeh.de/LambdaPi/) - just thought I'd get it back up to date!
> Update README to more closely align with direction

- src/semantics/mod.rs
- src/syntax/core.rs
This will be in preparation for deriving a `Subst` trait via the `moniker` library (see brendanzab/moniker#11).
> Move subststitutions into method on core::Term

- Cargo.toml
- src/semantics/errors.rs
- src/semantics/mod.rs
- src/semantics/tests/normalize.rs
- src/syntax/context.rs
- src/syntax/core.rs
- src/syntax/mod.rs
- src/syntax/pretty/core.rs
- src/syntax/prim.rs
- src/syntax/raw.rs
- src/syntax/translation/desugar/goldenfiles/ann
- src/syntax/translation/desugar/goldenfiles/ann_ann_ann
- src/syntax/translation/desugar/goldenfiles/ann_ann_left
- src/syntax/translation/desugar/goldenfiles/ann_ann_right
- src/syntax/translation/desugar/goldenfiles/id
- src/syntax/translation/desugar/goldenfiles/lam
- src/syntax/translation/desugar/goldenfiles/lam_lam_ann
- src/syntax/translation/desugar/goldenfiles/pi_pi
- src/syntax/translation/desugar/goldenfiles/ty
- src/syntax/translation/desugar/goldenfiles/ty_level
- src/syntax/translation/desugar/goldenfiles/var
- src/syntax/translation/desugar/goldenfiles/var_kebab_case
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/desugar/test.rs
- src/syntax/translation/resugar.rs
Also took the liberty of updating our other dependencies
> Update to Moniker v0.2.0

- book/.gitignore
- book/src/appendix/theory.md
- book/src/language/conditionals.md
- ci/build-highlight-js
- src/semantics/errors.rs
- src/semantics/mod.rs
- src/semantics/tests/check_term.rs
- src/semantics/tests/infer_term.rs
- src/syntax/concrete.rs
- src/syntax/core.rs
- src/syntax/parse/grammar.lalrpop
- src/syntax/parse/lexer.rs
- src/syntax/parse/mod.rs
- src/syntax/pretty/concrete.rs
- src/syntax/pretty/core.rs
- src/syntax/prim.rs
- src/syntax/raw.rs
- src/syntax/translation/desugar/goldenfiles/ann
- src/syntax/translation/desugar/goldenfiles/ann_ann_ann
- src/syntax/translation/desugar/goldenfiles/ann_ann_left
- src/syntax/translation/desugar/goldenfiles/ann_ann_right
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/resugar.rs
> Implement simple case expressions

- src/cli/repl.rs
- src/semantics/mod.rs
- src/semantics/normalize.rs
- src/semantics/tests/check_term.rs
- src/semantics/tests/infer_term.rs
- src/semantics/tests/mod.rs
- src/semantics/tests/normalize.rs
The semantics module is starting to get quite large, so moving this to a submodule might make things a little easier!
> Move normalization to submodule

- src/semantics/errors.rs
- src/semantics/mod.rs
- src/syntax/core.rs
- src/syntax/mod.rs
- src/syntax/pretty/core.rs
- src/syntax/raw.rs
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/resugar.rs
This will become more important once we can refer to items from other modules
> Create label wrapper types and use for module items

- book/src/appendix/theory.md
- src/library/prelude.pi
- src/semantics/errors.rs
- src/semantics/mod.rs
- src/semantics/tests/infer_term.rs
We need to change the type inference algorithm to get this to work - in this case allowing record values to be inferred.
> Use a nested record for primitive definitions

- src/semantics/mod.rs
- src/semantics/normalize.rs
- src/semantics/tests/infer_term.rs
- src/semantics/tests/normalize.rs
- src/syntax/concrete.rs
- src/syntax/core.rs
- src/syntax/parse/grammar.lalrpop
- src/syntax/pretty/concrete.rs
- src/syntax/pretty/core.rs
- src/syntax/raw.rs
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/resugar/mod.rs
This fixes pattern matching on booleans!
It does probably allow us to pattern match on types but don't tell anyone that...
> Add variable patterns

- book/src/appendix/theory.md
- src/semantics/mod.rs
- src/semantics/normalize.rs
- src/syntax/core.rs
- src/syntax/pretty/core.rs
- src/syntax/raw.rs
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/desugar/tests.rs
- src/syntax/translation/resugar/mod.rs
- src/syntax/translation/resugar/tests.rs
This simplifies the core language a bit more!
Closes #131.
> Desugar if expressions into case expressions

- src/semantics/env.rs
- src/semantics/mod.rs
- src/semantics/tests/infer_term.rs
- src/syntax/concrete.rs
- src/syntax/core.rs
- src/syntax/parse/grammar.lalrpop
- src/syntax/parse/lexer.rs
- src/syntax/pretty/concrete.rs
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/resugar/mod.rs
Attempted to clean some of this stuff up more. This more just moves the ickiness into the `env` module... oh well!
> Global cleanups

- src/semantics/errors.rs
- src/semantics/mod.rs
- src/semantics/normalize.rs
- src/syntax/concrete.rs
- src/syntax/core.rs
- src/syntax/parse/grammar.lalrpop
- src/syntax/pretty/concrete.rs
- src/syntax/pretty/core.rs
- src/syntax/raw.rs
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/resugar/mod.rs
- src/syntax/translation/resugar/tests.rs
This can just be pulled from the check phase
> Remove type annotation from extern terms

- book/src/appendix/theory.md
- book/src/language/universes.md
- src/semantics/mod.rs
- src/semantics/normalize.rs
- src/semantics/tests/infer_term.rs
- src/syntax/concrete.rs
- src/syntax/core.rs
- src/syntax/parse/grammar.lalrpop
- src/syntax/pretty/concrete.rs
- src/syntax/pretty/core.rs
- src/syntax/raw.rs
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/resugar/mod.rs
- src/syntax/translation/resugar/tests.rs
> Allow field projections to be shifted

- Cargo.toml
- src/syntax/mod.rs
This new version of moniker comes with some slight performance improvements when it comes to nested patterns. See brendanzab/moniker#56 for more details!
> Update to latest moniker

- book/src/language/conditionals.md
- src/semantics/tests/check_term.rs
- src/semantics/tests/infer_term.rs
- src/semantics/tests/normalize.rs
- src/syntax/concrete.rs
- src/syntax/parse/grammar.lalrpop
- src/syntax/parse/lexer.rs
- src/syntax/translation/desugar/tests.rs
Fixes #160.
Should be every occurrence.
> Removes `of` keyword from case expressions.

- .travis.yml
- Cargo.toml
- src/syntax/mod.rs
Closes #164
Closes #167
Closes #168
> Bump crate versions

- src/cli/repl.rs
- src/semantics/env.rs
- src/semantics/errors.rs
- src/semantics/mod.rs
- src/semantics/normalize.rs
- src/syntax/core.rs
- src/syntax/pretty/concrete.rs
- src/syntax/pretty/core.rs
- src/syntax/translation/desugar/mod.rs
- src/syntax/translation/desugar/tests.rs
- src/syntax/translation/resugar/mod.rs
This should make it clearer when we are using an immutable data stracutures as opposed to the data structures from std.
> Qualify usages of immutable hash maps

- book/README.md
- crates/README.md
- crates/pikelet-driver/Cargo.toml
- crates/pikelet-driver/README.md
- crates/pikelet-driver/src/lib.rs
- crates/pikelet-elaborate/Cargo.toml
- crates/pikelet-elaborate/README.md
- crates/pikelet-language-server/README.md
- crates/pikelet-library/Cargo.toml
- crates/pikelet-library/README.md
- crates/pikelet-repl/Cargo.toml
- crates/pikelet-repl/README.md
- crates/pikelet-repl/src/lib.rs
- crates/pikelet-syntax/Cargo.toml
- crates/pikelet-syntax/README.md
- crates/pikelet/README.md
- editors/README.md
Trying to make this new-fangled directory structure easier for peeps to navigate
> Cleanups and doc improvements after the Big Crate Breakup™️

- book/src/appendix/design.md
Cleaned up some stuff based on what we have learned since this document was first written
> Design doc updates

- crates/pikelet-driver/src/lib.rs
These were left over from the crate breakup in #172
> Remove some unused items

- crates/pikelet-concrete/src/desugar.rs
- crates/pikelet-concrete/src/elaborate/mod.rs
- crates/pikelet-concrete/src/resugar.rs
- crates/pikelet-concrete/src/syntax/raw.rs
- crates/pikelet-concrete/tests/desugar.rs
- crates/pikelet-concrete/tests/infer.rs
- crates/pikelet-concrete/tests/normalize.rs
- crates/pikelet-concrete/tests/parse.rs
- crates/pikelet-concrete/tests/resugar.rs
- crates/pikelet-core/src/nbe.rs
- crates/pikelet-core/src/syntax/core.rs
We can just use annotations for these
> Remove type annotations from lets in core syntax

- crates/pikelet-concrete/src/parse/grammar.lalrpop
- crates/pikelet-concrete/src/parse/lexer.rs
- crates/pikelet-concrete/src/parse/mod.rs
- crates/pikelet-concrete/src/syntax/concrete.rs
- crates/pikelet-driver/src/lib.rs
- crates/pikelet-driver/tests/prelude.rs
- crates/pikelet-repl/Cargo.toml
- crates/pikelet-repl/src/lib.rs
> Driver API cleanups

- pikelet/src/lang/core/semantics.rs
Missed these places when I added the `RecordTypeClosure::entries` function in #203.
> Use entries function in readback

- examples/functions.pi
- examples/prelude.pi
- pikelet-gui/src/lib.rs
- pikelet/src/lang/core.rs
- pikelet/src/lang/core/semantics.rs
- pikelet/src/lang/core/typing.rs
- pikelet/src/lang/surface.rs
- pikelet/src/lang/surface/grammar.lalrpop
- pikelet/src/lang/surface/lexer.rs
- pikelet/src/pass/core_to_pretty.rs
- pikelet/src/pass/core_to_surface.rs
- pikelet/src/pass/surface_to_core.rs
- pikelet/src/pass/surface_to_pretty.rs
- pikelet/tests/examples.rs
- website/docs/pikelet/roadmap.md
- website/docs/reference/functions.md
- website/docs/reference/names.md
- website/docs/reference/records.md
- website/src/theme/CodeBlock/pikelet.js
This implements dependent function types! 🎉
> Implement dependent function types

- pikelet-cli/src/repl.rs
- pikelet/src/lang/surface.rs
- pikelet/src/lang/surface/grammar.lalrpop
- pikelet/src/lang/surface/lexer.rs
- pikelet/src/reporting.rs
Converts parse errors into codespan diagnostics for prettier error reporting!
> Parse error improvements

- pikelet/src/pass/surface_to_core.rs
This ends up happening quite a bit in the elaborator, so making a method for it cleans things up somewhat!
> Add method for reading back to the surface language

- pikelet/src/lang/surface/grammar.lalrpop
This should reduce the size of the generated parser code a little.
> Inline some grammar productions

- pikelet-cli/Cargo.toml
- pikelet-cli/src/check.rs
- pikelet-cli/src/lib.rs
- pikelet-cli/src/repl.rs
- pikelet/src/lang/core/typing.rs
- pikelet/src/lang/surface.rs
- pikelet/src/pass/surface_to_core.rs
- pikelet/tests/examples.rs
This implements a rudimentary `pikelet check` command
> Implement check command

- pikelet/src/lang/core.rs
- pikelet/src/lang/core/semantics.rs
- pikelet/src/pass/surface_to_core.rs
This catches underflow errors that might occur!
> Return options from local level index conversions

- pikelet/src/pass/core_to_surface.rs
This fixes a name binding bug introduced in 8fce091c. We can’t just look up the names using the variable index when using a vector because new scopes are pushed onto the end of the environment - we first need to convert it to a level.
> Fix name assignment in distiller
