pikelet-lang/pikelet

src/cli/repl.rs

Fixes #3
So the problem seems to be that Rustyline returns an error if `Editor::load_history` is called with a file name that does not exist. Fix is just to ignore the error. The file will be created for the first time when `Editor::save_history` is called on closing the REPL.

Fix exit on missing REPL history file

---

Cargo.toml
book/src/index.md
book/src/language/index.md
src/cli/check.rs
src/cli/mod.rs
src/cli/repl.rs
src/lib.rs
src/semantics/errors.rs
src/semantics/tests.rs
src/syntax/translation/concrete_to_core.rs

Thanks to @Marwes’ [contributions to codespan](https://github.com/brendanzab/codespan/pull/5), we now have some pretty error reporting!
Closes #11

Bump codespan version to get pretty CLI reporting

---

Cargo.toml
book/src/SUMMARY.md
book/src/appendix/theory.md
book/src/language/conditionals.md
book/src/language/index.md
book/src/language/type-inference.md
src/library/prelude.pi
src/semantics/errors.rs
src/semantics/mod.rs
src/syntax/concrete.rs
src/syntax/core.rs
src/syntax/parse/grammar.lalrpop
src/syntax/parse/lexer.rs
src/syntax/pretty/concrete.rs
src/syntax/pretty/core.rs
src/syntax/translation/concrete_to_core.rs
src/syntax/translation/core_to_concrete.rs

We _could_ implement if expressions as as a mix-fix operator, with lazy arguments for the if-true and if-false branches. This is what [Idris does](https://github.com/idris-lang/Idris-dev/blob/d0e06806a256b402075e6a54ca172e7321fa576a/libs/prelude/Prelude/Bool.idr#L12-L18). That would require quite a bit more infrastructure however, so for now I figure it's easier just to add these to the core language.

Add booleans as primitive types and implement if expressions

---

book/src/appendix/references.md
book/src/appendix/theory.md
src/semantics/mod.rs
src/semantics/tests/normalize.rs
src/syntax/core.rs

This should fix #22. Alas it might be a little slow performace wise. It might be better to use weak head normal forms and explicit substitutions to improve laziness during type checking. This is a little trickier to get right, but I’ve been working on figuring this out in #56.

Eagerly apply substitutions

---

src/semantics/tests/check.rs
src/semantics/tests/check_module.rs
src/semantics/tests/infer.rs
src/semantics/tests/mod.rs
src/semantics/tests/normalize.rs
src/syntax/translation/concrete_to_core.rs

After peering for ages at the Debug output of the test failures in #47 I finally bit the bullet and used codespan_reporting for type errors in our tests.

Use better error reporting for tests

---

book/src/appendix/theory.md
book/src/language/records.md
src/semantics/errors.rs
src/semantics/mod.rs
src/semantics/tests/check.rs
src/semantics/tests/infer.rs
src/syntax/core.rs
src/syntax/pretty/core.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/resugar.rs

This PR builds atop #45, allowing the fields of record types to depend on the values of previous fields. This is important for allowing us to use records as modules.
Fixes #2.

Dependent Records (first pass) 

---

.travis.yml

Re-enabling Travis checking for Rust stable now that result-in-main and slice patterns have been stabilised. I’ve also pinned the lowest stable version to `1.26.0` as documentation for folks in the future.

Re-enable CI for Rust stable

---

src/semantics/errors.rs
src/semantics/mod.rs
src/syntax/context.rs
src/syntax/core.rs
src/syntax/pretty/core.rs
src/syntax/prim.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/resugar.rs

Not sure about this one. This makes primitive types just empty type claims in the context associated definitions. We can then just refer to them using free variables in the type checker. 🤷‍♂️

Remove hard-coded type constants

---

book/README.md
book/src/appendix/design.md
book/src/language/conditionals.md
book/src/language/functions.md
book/src/language/index.md
book/src/language/records.md
book/src/language/type-inference.md
book/src/language/types-of-types.md

docs: Fix typo: our -> or
docs: proceeded -> preceded
docs: Inline code block to more clearly reference `if` expression
docs: Use present tense for instruction
docs: Fix typo: thaw -> that
docs: Opinion: add comma for better structure
docs: Opinion: remove comma for better structure
docs: Fix typo: to -> too
docs: Opinion: add comma for better structure
docs: Fix missing preposition: list things -> list of things

docs: Fix minor typos, sentence structure in the Language Book

---

src/cli/repl.rs
src/semantics/errors.rs
src/semantics/mod.rs
src/semantics/tests/normalize.rs
src/syntax/context.rs
src/syntax/core.rs
src/syntax/pretty/core.rs
src/syntax/translation/resugar.rs

This greatly cleans up lots of the code, at the expense of potentially making it harder to debug ICEs. I had to do a lot of conjuring up of dummy spans at any rate, so I'm not sure how good those errors would have been at any rate. Spans are still retained in the raw syntax though - this is essential for good type error messages!

Remove span information from core syntax

---

Cargo.toml
src/lib.rs
src/semantics/tests/goldenfiles/ty
src/semantics/tests/normalize.rs
src/syntax/translation/desugar/goldenfiles/ann
src/syntax/translation/desugar/goldenfiles/ann_ann_ann
src/syntax/translation/desugar/goldenfiles/ann_ann_left
src/syntax/translation/desugar/goldenfiles/ann_ann_right
src/syntax/translation/desugar/goldenfiles/id
src/syntax/translation/desugar/goldenfiles/lam
src/syntax/translation/desugar/goldenfiles/lam_lam_ann
src/syntax/translation/desugar/goldenfiles/pi_pi
src/syntax/translation/desugar/goldenfiles/ty
src/syntax/translation/desugar/goldenfiles/ty_level
src/syntax/translation/desugar/goldenfiles/var
src/syntax/translation/desugar/goldenfiles/var_kebab_case
src/syntax/translation/desugar/test.rs

Partially resolves issue #78.
Could not refactor tests where the tested terms rely on a global name generator.

Use "goldenfiles" for some tests

---

src/semantics/mod.rs
src/syntax/core.rs
src/syntax/pretty/core.rs
src/syntax/raw.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/resugar.rs

This should fix potential shadowing of primitives.
I'm using the `nameless::Nest` type here, which creates a series of nested patterns (subsequent patterns can depend values bound in previous patterns).

Use nested patterns at top level

---

Cargo.toml
src/cli/repl.rs
src/lib.rs
src/semantics/errors.rs
src/semantics/mod.rs
src/semantics/tests/check_term.rs
src/semantics/tests/infer_term.rs
src/semantics/tests/mod.rs
src/semantics/tests/normalize.rs
src/syntax/concrete.rs
src/syntax/core.rs
src/syntax/parse/grammar.lalrpop
src/syntax/pretty/concrete.rs
src/syntax/pretty/core.rs
src/syntax/prim.rs
src/syntax/raw.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/resugar.rs

Doing some initial prep work for implementing pattern matching.
I moved the shared application 'spine' off the neutral variants, and pulled literals into a separate type in the concrete syntax. I also created separate `{infer,check}_literal` functions that can be reused once we add pattern type checking.

Preparatory work for implementing pattern matching

---

Cargo.toml
src/semantics/errors.rs
src/semantics/mod.rs
src/syntax/core.rs
src/syntax/mod.rs
src/syntax/pretty/core.rs
src/syntax/raw.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/resugar.rs

I was never really happy with the `Label` wrapper type. This follows how Unbound does it [in the `Functor2` example](https://github.com/sweirich/replib/blob/763ad146530b021eef108e2c889ebff6d750ee23/Unbound/Examples/Functor2.hs#L32-L35).

Remove Label type

---

src/cli/repl.rs
src/lib.rs
src/library/prelude.pi
src/semantics/errors.rs
src/semantics/mod.rs
src/semantics/tests/check_term.rs
src/semantics/tests/infer_term.rs
src/semantics/tests/mod.rs
src/semantics/tests/normalize.rs
src/syntax/concrete.rs
src/syntax/context.rs
src/syntax/core.rs
src/syntax/parse/grammar.lalrpop
src/syntax/parse/lexer.rs
src/syntax/pretty/concrete.rs
src/syntax/pretty/context.rs
src/syntax/pretty/core.rs
src/syntax/prim.rs
src/syntax/raw.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/resugar.rs

This adds an `extern` expression that can be used to declare primitives. For example:
```pikelet
prim-u64-eq = extern "u64-eq" : U64 -> U64 -> Bool
```
This means that primitive definitions are declared in the source language itself, meaning that we could potentially add documentation to these definitions in the future. It also makes it much easier to add type annotations to these definitions because the types are asserted in the source code, rather than in the Rust implementation.

Create an extern keyword for primitive definitions

---

Cargo.toml
src/cli/repl.rs
src/lib.rs

Rustyline seems dormant (kkawakam/rustyline#123), so this switches us over to linefeed. This cuts down on the very old dependencies that rustyline was pulling in, and will provide us with async support in the future.

Replace rustyline with linefeed

---

src/library/prelude.pi

This is just for fun, but I should really get around to deleting these at some stage! Or just moving them into tests. They aren’t that useful practically, and are at worst confusing to newcomers reading the prelude!

Fix church encoded types

---

src/cli/repl.rs
src/semantics/errors.rs
src/semantics/mod.rs
src/semantics/normalize.rs
src/semantics/tests/infer_term.rs
src/semantics/tests/normalize.rs
src/syntax/core.rs
src/syntax/pretty/core.rs
src/syntax/raw.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/resugar.rs

This should help going forward. There are several things this does not cover which will needed to be worked on in the future, namely recursion and mutual recursion, as well as type inference. `let x : I32; x = 5; in x` does not work in this version.
Another huge thing missing right now are tests. At the very least, all previous tests seem to pass and manual checking in the repl does what's expected.
This also includes a few refactors such as pulling code out of the module translation function to reuse for let-bindings and possibly in the future, records. In addition, I added `InternalError::Unimplemented{ feat: String }` to make it easier to stub behavior without panicking.

Preliminary implementation of let-bindings.

---

src/cli/check.rs
src/cli/repl.rs
src/lib.rs
src/semantics/tests/check_module.rs
src/semantics/tests/mod.rs
src/syntax/concrete.rs
src/syntax/parse/grammar.lalrpop
src/syntax/parse/lexer.rs
src/syntax/parse/mod.rs
src/syntax/pretty/concrete.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/desugar/tests.rs
src/syntax/translation/resugar/mod.rs

Working towards #15
Here we collect a list of import paths at parse time, whenever we hit an import expression. I'm not exactly sure how these will be used yet though...
I also don't really want to add import expressions to the core syntax. Import expressions also feel like they overlap a bit in functionality with extern expressions, so we might be able to simplify things there.
cc. @sordina, @boomshroom

Add stubbed out import expression syntax

---

src/cli/repl.rs
src/lib.rs

Eventually we'll want to open the record into the repl's environment, but this will work for now!
```
Pikelet> prelude.id String "hello"
"hello" : String
```
It also exposes how slow projections are! 😅
Closes #136

Load prelude on repl start

---

src/library/prelude.pi
src/syntax/concrete.rs
src/syntax/parse/grammar.lalrpop
src/syntax/pretty/concrete.rs
src/syntax/translation/desugar/mod.rs
src/syntax/translation/desugar/tests.rs
src/syntax/translation/resugar/mod.rs

This adds record field puns to the concrete syntax.
So, if `x` and `y` are bound in scope:
```
record { x = x; y = y }
```
could be written as:
```
record { x; y }
```

Add record field puns

---

src/library/prelude.pi
src/semantics/tests/infer_term.rs

This PR does the following:
- Adds a `Unit` type to the prelude
- Removes the old (kinda useless and confusing) church encoded types
- Uses a `where` expression to list the exports up the top of the file

Prelude cleanups

---

book/src/language/index.md

closes #159 
`of` is currently left out due to #160 
If there is a plan to use `of` in another way, I'll add it in ^^

Add a list of keywords to the docs

---

crates/pikelet-elaborate/src/context.rs
crates/pikelet-elaborate/src/errors.rs
crates/pikelet-elaborate/src/lib.rs
crates/pikelet-elaborate/src/normalize.rs
crates/pikelet-elaborate/tests/check.rs
crates/pikelet-elaborate/tests/infer.rs
crates/pikelet-elaborate/tests/normalize.rs
crates/pikelet-syntax/src/concrete.rs
crates/pikelet-syntax/src/core.rs
crates/pikelet-syntax/src/parse/errors.rs
crates/pikelet-syntax/src/parse/grammar.lalrpop
crates/pikelet-syntax/src/parse/mod.rs
crates/pikelet-syntax/src/pretty/concrete.rs
crates/pikelet-syntax/src/pretty/core.rs
crates/pikelet-syntax/src/raw.rs
crates/pikelet-syntax/src/translation/desugar.rs
crates/pikelet-syntax/src/translation/resugar.rs
crates/pikelet-syntax/tests/desugar.rs
crates/pikelet-syntax/tests/parse.rs
crates/pikelet-syntax/tests/resugar.rs

In [brendanzab/rust-nbe-for-mltt ](https://github.com/brendanzab/rust-nbe-for-mltt) I’ve used some less obscure names for the variants in the ASTs that I think improve clarity, and group together various related things.
The renamings that I’ve done are as follows:
- `Pi` → `FunType`
- `Arrow` → `FunArrow`
- `Lam` → `FunIntro`
- `App` → `FunApp`
- `Record` → `RecordIntro`
- `Proj` → `RecordProj`
- `Array` → `ArrayIntro`

Rename AST variants for clarity

---

examples/comments.pi
pikelet/Cargo.toml
pikelet/src/surface.rs
pikelet/src/surface/grammar.lalrpop
pikelet/src/surface/lex.rs
pikelet/tests/examples.rs
website/docs/pikelet/roadmap.md

So, this was an attempt to bring in a lexer generator, and make it work with the existing lalrpop parser.
I do have some reservations about the particular choice lexer, there is much to :heart: about the logos lexer, but it also doesn't seem particularly active, has some regex bugs :sob:, and can blow up exponentially with a bad choice of regex.
That said it seems to work well... the interface to lalrpop and errors does seem to involve quite a bit of boiler plate that I haven't managed to reduce the amount of.
I'm not relatively unversed in the CodeSpan dept, so hopefully it isn't doing anything terrible to errors, but that seems to be handled somehow above the parser?
I'm somewhat on the "well, it works for now, it could fairly easily be replaced if things go awry..." fence, but I would …

Next branch with logos lexer

---

.github/workflows/ci.yml
pikelet/src/lang/core.rs
pikelet/src/lang/core/semantics.rs
pikelet/src/lang/core/typing.rs
pikelet/src/pass/core_to_surface.rs
pikelet/src/pass/surface_to_core.rs
pikelet/tests/examples.rs

Rather than splitting record types into `Value::RecordTypeExtend` and `Value::RecordTypeEmpty` during evaluation,  this commit captures all the record entry types at once in a `RecordClosure` and puts this in a single `Value::RecordType` variant. This reduces some indirection, reduces some copyies, and should make it easier to compare records with out of order fields in the future.

Reduce indirection in record types

---

pikelet-cli/src/repl.rs
pikelet/src/lang/core.rs
pikelet/src/lang/core/semantics.rs
pikelet/src/lang/core/typing.rs
pikelet/src/lang/surface.rs
pikelet/src/lang/surface/grammar.lalrpop
pikelet/src/lang/surface/lexer.rs
pikelet/src/lib.rs
pikelet/src/pass/core_to_pretty.rs
pikelet/src/pass/core_to_surface.rs
pikelet/src/pass/surface_to_core.rs
pikelet/src/pass/surface_to_core/reporting.rs
pikelet/src/pass/surface_to_pretty.rs
website/docs/reference/functions.md
website/docs/reference/names.md
website/docs/reference/records.md

This implements name avoidance in the delaboration pass. This should make it easier to finish implementing #200 and #201! We also add a syntax for explicit binder names in record types to handle the rare case when we have a conflict with the record label and an existing binder in scope.

Implement name avoidance in delaborator

---

pikelet/Cargo.toml
pikelet/src/lang/core.rs
pikelet/src/lang/core/semantics.rs
pikelet/src/lang/core/typing.rs
pikelet/src/pass/surface_to_core.rs

This uses glued evaluation to improve the terms returned from readback. This will allow us to create an explicitly typed core language without worrying about [potential term-size blowups](https://twitter.com/brendanzab/status/1283278258818002944) that can occur from excessive unfolding of definitions.

Interpreter improvements

---

pikelet-cli/src/repl.rs
pikelet/src/lang/core/typing.rs
pikelet/src/pass/core_to_surface.rs
pikelet/src/pass/surface_to_core.rs
pikelet/tests/examples.rs

This converts the typing and translation pass functions into methods on their `State` type. I'm unsure if this is an improvement or not!
The short of it is that instead of:
```rust
let (core_term, r#type) = surface_to_core::synth_type(&mut state, &surface_term);
```
you now write:
```rust
let (core_term, r#type) = state.synth_type(&surface_term);
```

Use state methods instead of free functions

---

pikelet/Cargo.toml
pikelet/src/lang/core/semantics.rs
pikelet/src/lang/core/typing.rs
pikelet/src/pass/core_to_surface.rs
pikelet/src/pass/surface_to_core.rs

This uses @karroffel's [`contracts`](https://lib.rs/crates/contracts) crate to enforce and document some of the postconditions on some of the state functions. This should help avoid [some bugs](https://github.com/pikelet-lang/pikelet/pull/201#discussion_r422456357) in the future!

Add some postconditions to stateful methods

---

pikelet/src/lang/core/typing.rs
pikelet/src/pass/surface_to_core.rs

Not sure why I had these on here, but they are not needed!

Remove unnecessary &mut from report methods

---

pikelet-cli/src/repl.rs
pikelet-editor/src/lib.rs
pikelet/src/lang/core.rs
pikelet/src/lang/core/semantics.rs
pikelet/src/lang/core/typing.rs
pikelet/src/pass/core_to_pretty.rs
pikelet/src/pass/core_to_surface.rs
pikelet/src/pass/surface_to_core.rs

This adds range information to the core language. This should be useful for debug information later on, and for improved validation errors.

Add range information to core language

---

pikelet-cli/src/repl.rs
pikelet/src/lang/core/semantics.rs
pikelet/src/lang/core/typing.rs
pikelet/src/pass/surface_to_core.rs

This makes some of the elaboration and type checking code a bit cleaner and more succinct!

Shorten function names

---

pikelet/src/lang/core.rs
pikelet/src/lang/core/semantics.rs
pikelet/src/lang/core/typing.rs
pikelet/src/pass/core_to_pretty.rs
pikelet/src/pass/core_to_surface.rs
pikelet/src/pass/surface_to_core.rs

This groups the conversions back on the `LocalSize` type, which I think makes a bit more sense.

Rework local variable API and improve docs

---

.github/workflows/ci.yml
pikelet/src/lang.rs
pikelet/src/lang/core/marshall.rs
pikelet/src/reporting.rs

The const generics MVP [landed in Rust 1.51.0](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html)! This lets us remove some uses of macros.

Remove some macros in favor of const generics

---

examples/meta.pi
pikelet/tests/examples.rs

I thought this was fun! I was inspired by how [Dhall encodes ASTs](https://github.com/dhall-lang/dhall-lang/blob/master/Prelude/JSON/Type.dhall), in lieu of implementing inductive types.

Add Pikelet AST example

---

pikelet-editor/src/lib.rs
pikelet/src/lang/core.rs
pikelet/src/lang/core/semantics.rs
pikelet/src/lang/core/typing.rs
pikelet/src/lib.rs
pikelet/src/pass/core_to_pretty.rs
pikelet/src/pass/core_to_surface.rs
pikelet/src/pass/surface_to_core.rs
pikelet/src/reporting.rs

I've been pondering this for a while now, but then when I saw [John Sterling do it in dreamtt](https://github.com/jonsterling/dreamtt/blob/aa30a57ca869e91a295e586773a892c6601b5ddb/core/Syntax.ml#L34-L56) I thought it was pretty neat! It increases some sharing between the arrays of record labels, and makes the 'label' and 'telescope' parts of dependent records more distinct.

Improve sharing between record labels

---

examples/record-term-deps.pi
examples/record-type-deps.pi
pikelet/src/lang/core/semantics.rs

Previously we were seeing this buggy behaviour:
```
> (record { A = S32, a = 1 } : Record { A : Type, a : A }).a
1 : 1
```
This was because we were using the wrong label in our call to `record_elim` - using the label of the entire record elimination, rather than the current field of the iteration.
After the fix we see something a bit more sensible!
```
> (record { A = S32, a = 1 } : Record { A : Type, a : A }).a
1 : S32
```

Fix bug in type checking of record eliminations

---

pikelet-cli/Cargo.toml
pikelet-cli/tests/source_tests.rs
pikelet-test/Cargo.toml
pikelet-test/src/lib.rs
pikelet/src/lang/core.rs
pikelet/src/lang/core/typing.rs
pikelet/src/pass/surface_to_core.rs

This uses the fantastic [libtest-mimic](https://lib.rs/crates/libtest-mimic) crate to build up a test harness dynamically. Later on we can add support for finer grained testing, for example adding underlines in comments for expected diagnostics, and snapshot tests for expected console output.
Closes #180

Automatically discover integration tests
